version: "3.4"

services:
  traefik:
    image: traefik:v2.2
    security_opt:
      - no-new-privileges:true
    container_name: traefik
    restart: unless-stopped
    # command: 
      # --api.insecure=true --providers.docker
    networks:
      - web
      - internal
    ports:
      - "80:80"
      - "443:443"
    environment:
    environment:
      #- GCE_PROJECT=twowheelstogo-572d7
      - GCE_SERVICE_ACCOUNT_FILE=key.json
      #- GCE_SERVICE_ACCOUNT=traefik-ecommerce@twowheelstogo-572d7.iam.gserviceaccount.com
      - GOOGLE_APPLICATION_CREDENTIALS=key.json
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/reaction/proxy/traefik/traefik.yml:/traefik.yml:ro
      - /home/reaction/proxy/traefik/acme.json:/acme.json
      - /home/reaction/proxy/traefik/key.json:/key.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.qubit01.systems`)"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
      # - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.qubit01.systems`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=le"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=qubit01.systems"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.qubit01.systems"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  web:
    external:
      name: web
  internal:
    external:
      name: internal
