version: "3.4"

networks:
  web:
    external:
      name: web
  internal:
    external:
      name: internal

services:
  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    networks:
      - internal

  portainer:
    image: portainer/portainer
    restart: always
    container_name: "portainer-app"
    labels:
      - "traefik.backend=portainer"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:portainer.example.com"
    #Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    command: --templates http://templates/templates.json
    networks:
      - web
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  watchtower:
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer-data:
